version: "3.9"

services:
    # database service
    mongo_db:
      container_name: mongo_db_container
      image: mongo:latest
      restart: always
      ports:
        - "2717:27017"
      volumes:
        - mongo_db:/data/db


    
    # node api service
    node_api:
        container_name: node_api_container
        build: 
            context: .
        ports: 
          - "4000:3000"
        environment:
          PORT: 3000
          DB_HOST: mongo_db
          DB_PORT: 27017
          DB_COLLECTION: slot
          MONGO_INITDB_ROOT_USERNAME: admin
          MONGO_INITDB_ROOT_PASSWORD: adminx
          MONGO_INITDB_DATABASE: slotdb
          

        depends_on:
            - mongo_db

        volumes:
            - ./src:/usr/src/app/src

volumes:
    mongo_db: {}

